//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoDoLuong.Web.Areas.Manage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRole
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
